name: Merge upstream branches
on:
  schedule:
    - cron:  '*/10 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'mistium'
          git config --global user.email 'mistium@users.noreply.github.com'

          git pull --unshallow

          git remote add upstream https://github.com/Sakamoto9016/I2c.git
          git fetch upstream

          git checkout -b feature/x origin/feature/x
          git merge --no-edit upstream/feature/x
          git push origin feature/x

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
